import { useEffect } from "react";
import { listen } from "../../lib/ipc";
import { useVoiceStore } from "../../stores/voiceStore";

interface StreamThumbnailPayload {
  ownerUsername: string;
  thumbnailBase64: string; // pre-prefixed `data:image/jpeg;base64,…` URL
}

/**
 * Listens for `stream_thumbnail_updated` events.
 * Thumbnails are generated by the streamer's video pipeline and
 * broadcast to all voice channel participants via TCP. We only store
 * thumbnails for streams the user is *not* actively watching (those
 * already have live video).
 */
export function useStreamThumbnails() {
  const activeStreams = useVoiceStore((s) => s.activeStreams);

  useEffect(() => {
    if (activeStreams.length === 0) return;

    const unlisten = listen<StreamThumbnailPayload>(
      "stream_thumbnail_updated",
      (event) => {
        const { ownerUsername, thumbnailBase64 } = event.payload;
        const state = useVoiceStore.getState();
        if (state.watchingStreams.includes(ownerUsername)) return;
        if (
          state.activeStreams.some((s) => s.ownerUsername === ownerUsername)
        ) {
          state.setStreamThumbnail(ownerUsername, thumbnailBase64);
        }
      },
    );

    return () => {
      unlisten.then((fn) => fn());
    };
  }, [activeStreams.length]);
}
