import { useEffect } from "react";
import { useVoiceStore } from "../../stores/voiceStore";

/**
 * Listens for stream thumbnails on the dedicated binary IPC channel
 * (`window.decibell.streamThumbnails.subscribe`). Thumbnails are
 * generated by the streamer's video pipeline and broadcast to all
 * voice channel participants via TCP. We only store thumbnails for
 * streams the user is *not* actively watching (those already have
 * live video).
 *
 * The channel hands us raw JPEG bytes — we wrap them in a
 * `URL.createObjectURL(new Blob(...))` and stash that URL on the
 * voice store. The store revokes the previous URL before replacing
 * it, so blob storage stays bounded as fresh thumbnails arrive every
 * few seconds per active stream.
 *
 * Pre-PR8 path used a `data:image/jpeg;base64,…` URL pre-rendered in
 * Rust and shipped through the JSON event bus — that cost ~33% byte
 * inflation on every payload and a base64 encode/decode pass on each
 * end. Binary channel + blob URL = same `<img src=>` ergonomics with
 * none of the transcoding.
 */
export function useStreamThumbnails() {
  const activeStreams = useVoiceStore((s) => s.activeStreams);

  useEffect(() => {
    if (activeStreams.length === 0) return;

    const unsubscribe = window.decibell.streamThumbnails.subscribe((thumb) => {
      const state = useVoiceStore.getState();
      const { ownerUsername, data } = thumb;
      // Skip if the user is actively watching this stream — they
      // already have live video, no need for a poster frame.
      if (state.watchingStreams.includes(ownerUsername)) return;
      // Skip if the stream has already gone away in the time it took
      // the thumbnail to land (race vs. a stop_streaming presence
      // update). Avoids briefly stashing a blob URL that nothing
      // would ever revoke.
      if (!state.activeStreams.some((s) => s.ownerUsername === ownerUsername)) {
        return;
      }
      const blob = new Blob([data], { type: "image/jpeg" });
      const url = URL.createObjectURL(blob);
      state.setStreamThumbnail(ownerUsername, url);
    });

    return () => {
      unsubscribe();
    };
  }, [activeStreams.length]);
}
