import { useEffect } from "react";
import { listen } from "@tauri-apps/api/event";
import { useVoiceStore } from "../../stores/voiceStore";

interface StreamThumbnailPayload {
  ownerUsername: string;
  thumbnailBase64: string; // data:image/jpeg;base64,... URL
}

/**
 * Listens to stream_thumbnail_updated events from the backend.
 * Thumbnails are generated by the streamer's video pipeline and
 * broadcast to all voice channel participants via TCP.
 */
export function useStreamThumbnails() {
  const activeStreams = useVoiceStore((s) => s.activeStreams);

  useEffect(() => {
    if (activeStreams.length === 0) return;

    const unlisten = listen<StreamThumbnailPayload>(
      "stream_thumbnail_updated",
      (event) => {
        const { ownerUsername, thumbnailBase64 } = event.payload;
        const state = useVoiceStore.getState();
        // Skip thumbnails for streams we're watching (they have live video)
        if (state.watchingStreams.includes(ownerUsername)) return;
        // Only store thumbnails for active streams
        if (state.activeStreams.some((s) => s.ownerUsername === ownerUsername)) {
          state.setStreamThumbnail(ownerUsername, thumbnailBase64);
        }
      }
    );

    return () => {
      unlisten.then((fn) => fn());
    };
  }, [activeStreams.length > 0]);
}
