/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm64.node')
          } else {
            nativeBinding = require('decibell-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm-eabi.node')
          } else {
            nativeBinding = require('decibell-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-x64-msvc.node')
          } else {
            nativeBinding = require('decibell-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('decibell-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('decibell-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'index.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.darwin-universal.node')
      } else {
        nativeBinding = require('decibell-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'index.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-x64.node')
          } else {
            nativeBinding = require('decibell-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-arm64.node')
          } else {
            nativeBinding = require('decibell-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'index.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.freebsd-x64.node')
      } else {
        nativeBinding = require('decibell-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-musl.node')
            } else {
              nativeBinding = require('decibell-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-gnu.node')
            } else {
              nativeBinding = require('decibell-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-musl.node')
            } else {
              nativeBinding = require('decibell-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('decibell-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('decibell-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('decibell-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('decibell-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('decibell-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'index.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('decibell-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { login, register, logout, uploadAvatar, fetchAvatar, requestChannelHistory, wipeChannelHistory, updateChannelRetention, sendChannelMessage, listMembers, kickMember, banMember, leaveServer, createInvite, listInvites, revokeInvite, requestFriendList, sendFriendAction, sendPrivateMessage, requestServerList, connectToCommunity, redeemInvite, disconnectFromCommunity, parseInviteLink, resolveInviteCode, getAttachmentTarget, loadConfig, saveSettings, setDmPrivacy, setTransferLimits, listAudioDevices, startScreenShare, stopScreenShare, sendVideoFrame, watchStream, stopWatching, fetchStreamThumbnail, getCaps, setEncoderCaps, setDecoderCaps, getCodecSettings, setCodecSettings, sendStreamThumbnail, probeNativeEncoders, forceKeyframe, joinVoiceChannel, leaveVoiceChannel, setVoiceMute, setVoiceDeafen, setVoiceThreshold, setStreamVolume, setStreamStereo, setUserVolume, setAecEnabled, setNoiseSuppressionLevel, setAgcEnabled, setInputDevice, setOutputDevice, setSeparateStreamOutput, setStreamOutputDevice, init, shutdown, ping, pingAsync } = nativeBinding

module.exports.login = login
module.exports.register = register
module.exports.logout = logout
module.exports.uploadAvatar = uploadAvatar
module.exports.fetchAvatar = fetchAvatar
module.exports.requestChannelHistory = requestChannelHistory
module.exports.wipeChannelHistory = wipeChannelHistory
module.exports.updateChannelRetention = updateChannelRetention
module.exports.sendChannelMessage = sendChannelMessage
module.exports.listMembers = listMembers
module.exports.kickMember = kickMember
module.exports.banMember = banMember
module.exports.leaveServer = leaveServer
module.exports.createInvite = createInvite
module.exports.listInvites = listInvites
module.exports.revokeInvite = revokeInvite
module.exports.requestFriendList = requestFriendList
module.exports.sendFriendAction = sendFriendAction
module.exports.sendPrivateMessage = sendPrivateMessage
module.exports.requestServerList = requestServerList
module.exports.connectToCommunity = connectToCommunity
module.exports.redeemInvite = redeemInvite
module.exports.disconnectFromCommunity = disconnectFromCommunity
module.exports.parseInviteLink = parseInviteLink
module.exports.resolveInviteCode = resolveInviteCode
module.exports.getAttachmentTarget = getAttachmentTarget
module.exports.loadConfig = loadConfig
module.exports.saveSettings = saveSettings
module.exports.setDmPrivacy = setDmPrivacy
module.exports.setTransferLimits = setTransferLimits
module.exports.listAudioDevices = listAudioDevices
module.exports.startScreenShare = startScreenShare
module.exports.stopScreenShare = stopScreenShare
module.exports.sendVideoFrame = sendVideoFrame
module.exports.watchStream = watchStream
module.exports.stopWatching = stopWatching
module.exports.fetchStreamThumbnail = fetchStreamThumbnail
module.exports.getCaps = getCaps
module.exports.setEncoderCaps = setEncoderCaps
module.exports.setDecoderCaps = setDecoderCaps
module.exports.getCodecSettings = getCodecSettings
module.exports.setCodecSettings = setCodecSettings
module.exports.sendStreamThumbnail = sendStreamThumbnail
module.exports.probeNativeEncoders = probeNativeEncoders
module.exports.forceKeyframe = forceKeyframe
module.exports.joinVoiceChannel = joinVoiceChannel
module.exports.leaveVoiceChannel = leaveVoiceChannel
module.exports.setVoiceMute = setVoiceMute
module.exports.setVoiceDeafen = setVoiceDeafen
module.exports.setVoiceThreshold = setVoiceThreshold
module.exports.setStreamVolume = setStreamVolume
module.exports.setStreamStereo = setStreamStereo
module.exports.setUserVolume = setUserVolume
module.exports.setAecEnabled = setAecEnabled
module.exports.setNoiseSuppressionLevel = setNoiseSuppressionLevel
module.exports.setAgcEnabled = setAgcEnabled
module.exports.setInputDevice = setInputDevice
module.exports.setOutputDevice = setOutputDevice
module.exports.setSeparateStreamOutput = setSeparateStreamOutput
module.exports.setStreamOutputDevice = setStreamOutputDevice
module.exports.init = init
module.exports.shutdown = shutdown
module.exports.ping = ping
module.exports.pingAsync = pingAsync
