/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LoginArgs {
  username: string
  password: string
}
export declare function login(args: LoginArgs): Promise<void>
export interface RegisterArgs {
  username: string
  email: string
  password: string
}
export declare function register(args: RegisterArgs): Promise<void>
export declare function logout(): Promise<void>
export interface UploadAvatarResult {
  success: boolean
  message: string
  /** sha256-hex of the uploaded bytes; '' on removal. */
  version: string
}
export interface UploadAvatarArgs {
  jpeg: Buffer
}
/**
 * Upload or remove the authenticated user's avatar. Empty `jpeg`
 * argument = remove. Returns the server-computed sha256-hex version
 * on success.
 */
export declare function uploadAvatar(args: UploadAvatarArgs): Promise<UploadAvatarResult>
export interface FetchAvatarResult {
  version: string
  /** Empty Buffer when version == '' (no avatar). */
  data: Buffer
}
export interface FetchAvatarArgs {
  username: string
}
/**
 * Fetch a specific user's avatar bytes + current version. Empty
 * version + empty data means the user has no avatar (or doesn't
 * exist — same response shape).
 */
export declare function fetchAvatar(args: FetchAvatarArgs): Promise<FetchAvatarResult>
export interface RequestChannelHistoryArgs {
  serverId: string
  channelId: string
  /** 0 means most-recent; non-zero gets older messages for pagination. */
  beforeId: number
  limit: number
}
export declare function requestChannelHistory(args: RequestChannelHistoryArgs): Promise<void>
export interface WipeChannelHistoryArgs {
  serverId: string
  channelId: string
}
/**
 * Owner-only: nuke every message and attachment in `channel_id`.
 * Server validates ownership, applies the wipe, replies with a
 * CHANNEL_WIPE_RES (deleted counts) and broadcasts a CHANNEL_WIPED to
 * every member so their local state drops the channel's history
 * without re-fetching. The IPC returns immediately after the packet
 * is queued — the result lands later as the `channel_wipe_responded`
 * bus event.
 */
export declare function wipeChannelHistory(args: WipeChannelHistoryArgs): Promise<void>
export interface UpdateChannelRetentionArgs {
  serverId: string
  channelId: string
  retentionDaysText: number
  retentionDaysImage: number
  retentionDaysVideo: number
  retentionDaysDocument: number
  retentionDaysAudio: number
}
/**
 * Owner-only retention edit. All five values are sent as a snapshot;
 * 0 means "keep forever".
 */
export declare function updateChannelRetention(args: UpdateChannelRetentionArgs): Promise<void>
export interface SendChannelMessageArgs {
  serverId: string
  channelId: string
  message: string
  /**
   * Previously-uploaded attachment ids to bind to this message.
   * Server verifies ownership, channel scope, and 'ready' status —
   * anything that doesn't pass is silently dropped from the broadcast.
   * PR4 only sends text; this stays in the contract so PR-attachments
   * can light it up without an API change.
   */
  attachmentIds?: Array<number>
  /**
   * Client-generated UUID for optimistic-bubble dedup. Server echoes
   * it in the broadcast so the sending client can match the real
   * message back to its own optimistic placeholder.
   */
  nonce?: string
}
export declare function sendChannelMessage(args: SendChannelMessageArgs): Promise<void>
export interface ListMembersArgs {
  serverId: string
}
export declare function listMembers(args: ListMembersArgs): Promise<void>
export interface KickMemberArgs {
  serverId: string
  username: string
  reason: string
}
export declare function kickMember(args: KickMemberArgs): Promise<void>
export interface BanMemberArgs {
  serverId: string
  username: string
  reason: string
}
export declare function banMember(args: BanMemberArgs): Promise<void>
export interface LeaveServerArgs {
  serverId: string
}
export declare function leaveServer(args: LeaveServerArgs): Promise<void>
export interface CreateInviteArgs {
  serverId: string
  /** Unix epoch seconds. 0 means "never expires". */
  expiresAt: number
  /** 0 means "unlimited uses". */
  maxUses: number
}
export declare function createInvite(args: CreateInviteArgs): Promise<void>
export interface ListInvitesArgs {
  serverId: string
}
export declare function listInvites(args: ListInvitesArgs): Promise<void>
export interface RevokeInviteArgs {
  serverId: string
  code: string
}
export declare function revokeInvite(args: RevokeInviteArgs): Promise<void>
export declare function requestFriendList(): Promise<void>
export interface SendFriendActionArgs {
  /**
   * Maps to the protobuf FriendActionType enum:
   * 0 = ADD, 1 = REMOVE, 2 = BLOCK, 3 = ACCEPT, 4 = REJECT.
   */
  action: number
  targetUsername: string
}
export declare function sendFriendAction(args: SendFriendActionArgs): Promise<void>
export interface SendPrivateMessageArgs {
  recipient: string
  message: string
}
export declare function sendPrivateMessage(args: SendPrivateMessageArgs): Promise<void>
/**
 * Ask the central server for the user's server list. The response
 * arrives asynchronously as a `server_list_received` event.
 */
export declare function requestServerList(): Promise<void>
export interface ConnectToCommunityArgs {
  serverId: string
  host: string
  port: number
}
export declare function connectToCommunity(args: ConnectToCommunityArgs): Promise<void>
export interface RedeemInviteArgs {
  serverId: string
  host: string
  port: number
  inviteCode: string
}
/**
 * Connect to a community server while consuming an invite code so the
 * user joins (becomes a persistent member) as part of the handshake.
 */
export declare function redeemInvite(args: RedeemInviteArgs): Promise<void>
export interface DisconnectFromCommunityArgs {
  serverId: string
}
export declare function disconnectFromCommunity(args: DisconnectFromCommunityArgs): Promise<void>
export interface ParseInviteLinkArgs {
  url: string
}
export interface ParsedInviteLink {
  host: string
  port: number
  code: string
}
/**
 * Parse a `decibell://` invite URL into its components. Accepted shapes:
 *   decibell://invite/<host>:<port>/<code>
 *   decibell://invite/<host>/<port>/<code>
 *   decibell:invite/<host>:<port>/<code>
 */
export declare function parseInviteLink(args: ParseInviteLinkArgs): ParsedInviteLink
export interface ResolveInviteCodeArgs {
  code: string
}
export interface ResolvedInvite {
  host: string
  port: number
  code: string
}
/**
 * Ask the central server to resolve a raw invite code to a community
 * host:port. Returns the resolved endpoint or an error describing why
 * the code couldn't be resolved (unknown, expired, central not
 * reachable). Times out after 5 seconds.
 */
export declare function resolveInviteCode(args: ResolveInviteCodeArgs): Promise<ResolvedInvite>
export interface GetAttachmentTargetArgs {
  serverId: string
}
export interface AttachmentTarget {
  host: string
  port: number
  jwt: string
  /** Per-file upload cap reported by the server. 0 = unlimited. */
  maxAttachmentBytes: number
}
/**
 * Resolve the HTTPS endpoint for attachment uploads/downloads against a
 * connected community server. Returns null when the server didn't
 * advertise an attachment port (older builds, or HTTP disabled).
 * Renderer drives the actual transfer — this command just hands over
 * the host/port/jwt so `fetch()` can run with native HTTP/2 +
 * connection reuse + Chromium's TLS stack.
 */
export declare function getAttachmentTarget(args: GetAttachmentTargetArgs): Promise<AttachmentTarget | null>
/**
 * Read the persisted config blob from disk. Returns
 * `{ credentials, settings }` as a JSON value so the renderer can
 * hydrate its zustand stores without us having to re-declare the
 * whole AppSettings shape as a #[napi(object)] mirror (it has a
 * HashMap field which napi(object) doesn't support natively).
 */
export declare function loadConfig(): Promise<any>
/**
 * Persist a complete AppSettings blob to disk, preserving any
 * existing credentials. Renderer is the source of truth for the
 * settings shape; native just deserializes via serde and writes.
 * Mirrors tauri-client's save_settings: settings come from the
 * renderer as an object, we round-trip through serde_json::Value
 * into AppSettings.
 */
export declare function saveSettings(settings: any): Promise<void>
export interface SetDmPrivacyArgs {
  friendsOnly: boolean
}
/**
 * Tell the central server whether to deliver DMs from non-friends.
 * Mirrors the tauri command of the same name (defined there in
 * commands/messaging.rs). Lives in settings.rs here because the DM
 * command surface hasn't ported yet — when it does, this can move.
 */
export declare function setDmPrivacy(args: SetDmPrivacyArgs): Promise<void>
export interface SetTransferLimitsArgs {
  uploadBps: number
  downloadBps: number
}
/**
 * Persist the user's per-file upload/download caps. PR8 attachment
 * transfers happen renderer-side via Electron main's netFetch, so the
 * caps would have to be enforced there to actually rate-limit — for
 * now this command just writes them to AppSettings so they survive
 * across restarts. Live enforcement is a follow-up; the renderer's
 * saveSettings() will already include these fields, but exposing the
 * command keeps the call shape compatible with tauri-client's
 * NetworkTab.
 */
export declare function setTransferLimits(args: SetTransferLimitsArgs): Promise<void>
export interface AudioDevice {
  name: string
  label: string
}
export interface AudioDeviceList {
  inputs: Array<AudioDevice>
  outputs: Array<AudioDevice>
}
export declare function listAudioDevices(): Promise<AudioDeviceList>
export interface StartScreenShareArgs {
  serverId: string
  channelId: string
  fps: number
  width: number
  height: number
  videoBitrateKbps: number
  shareAudio: boolean
  audioBitrateKbps: number
  /**
   * VideoCodec byte: 1=H264_HW, 2=H264_SW, 3=H265, 4=AV1.
   * 0 means "no enforcement, LCD picker chooses initial codec".
   */
  initialCodec: number
  /** 0 = no enforcement, otherwise locks the stream to this codec. */
  enforcedCodec: number
  /**
   * Chromium desktopCapturer source id ("screen:N:0" or "window:HWND:0").
   * Required on Windows where native opens the source via WGC.
   * Optional on Linux/macOS where the renderer's getDisplayMedia
   * handles the picker via xdg-desktop-portal / ScreenCaptureKit.
   */
  sourceId?: string
}
export declare function startScreenShare(args: StartScreenShareArgs): Promise<void>
export interface StopScreenShareArgs {
  serverId: string
  channelId: string
}
export declare function stopScreenShare(args: StopScreenShareArgs): Promise<void>
/**
 * PR8 hot path: renderer's WebCodecs.VideoEncoder produces encoded
 * chunks; we packetise + UDP. Called once per encoded frame at the
 * configured FPS — needs to be cheap.
 */
export interface SendVideoFrameArgs {
  /** 1=H264_HW, 2=H264_SW, 3=H265, 4=AV1. */
  codec: number
  keyframe: boolean
  /**
   * Encoded chunk bytes. Typed as `Buffer` (not `Vec<u8>`) so napi-rs
   * accepts a JS `Uint8Array` directly without copying the bytes
   * through V8's array-conversion path. The renderer sends one of
   * these per encoded frame, so the per-frame allocation savings
   * matter.
   */
  data: Buffer
  /**
   * hvcC / av1C / avcC bytes for keyframes when the encoder produces
   * them out-of-band (WebCodecs `metadata.decoderConfig.description`).
   * Receivers use this directly to configure WebCodecs.VideoDecoder.
   * Optional — for H.264 in Annex B with inline SPS/PPS, the decoder
   * reads from the bitstream itself.
   */
  description?: Buffer
}
export declare function sendVideoFrame(args: SendVideoFrameArgs): void
export interface WatchStreamArgs {
  serverId: string
  channelId: string
  targetUsername: string
}
export declare function watchStream(args: WatchStreamArgs): Promise<void>
export interface StopWatchingArgs {
  serverId: string
  channelId: string
  targetUsername: string
}
export declare function stopWatching(args: StopWatchingArgs): Promise<void>
export interface FetchStreamThumbnailArgs {
  serverId: string
  username: string
}
export interface FetchStreamThumbnailResult {
  username: string
  /**
   * Empty Buffer when the server has no cached thumbnail yet
   * (stream just started, or fetch arrived between frames).
   */
  jpeg: Buffer
}
/**
 * On-demand fetch of the latest thumbnail for a streaming user.
 * Called by the renderer when UserProfilePopup opens for a user
 * known to be streaming. Returns empty bytes when no frame is
 * cached yet — caller renders the gradient placeholder.
 *
 * Same shape as `fetch_avatar` in commands/auth.rs: single-slot
 * oneshot per username, 5-second timeout, slot cleanup on timeout.
 */
export declare function fetchStreamThumbnail(args: FetchStreamThumbnailArgs): Promise<FetchStreamThumbnailResult>
export interface CodecCapValue {
  /** 1=H264_HW, 2=H264_SW, 3=H265, 4=AV1. */
  codec: number
  maxWidth: number
  maxHeight: number
  maxFps: number
}
export interface CapsResponse {
  encode: Array<CodecCapValue>
  decode: Array<CodecCapValue>
}
export declare function getCaps(): Promise<CapsResponse>
export interface SetEncoderCapsArgs {
  encoderCaps: Array<CodecCapValue>
}
export declare function setEncoderCaps(args: SetEncoderCapsArgs): Promise<void>
export interface SetDecoderCapsArgs {
  decoderCaps: Array<CodecCapValue>
}
export declare function setDecoderCaps(args: SetDecoderCapsArgs): Promise<void>
/**
 * Codec preference toggles persisted in the on-disk config. The
 * streaming UI reads these to gray out codecs the user has opted out
 * of. They also feed the toggle filter applied to encoder caps before
 * they ship in JoinVoiceRequest.
 */
export interface CodecSettingsValue {
  useAv1: boolean
  useH265: boolean
}
export declare function getCodecSettings(): Promise<CodecSettingsValue>
export declare function setCodecSettings(args: CodecSettingsValue): Promise<void>
export interface SendStreamThumbnailArgs {
  serverId: string
  channelId: string
  /**
   * JPEG bytes. Typed as `Buffer` (not `Vec<u8>`) so napi-rs
   * accepts a JS `Uint8Array` directly without forcing the
   * renderer to materialise a plain Array — `Vec<u8>` would
   * reject the typed-array shape with "not an array".
   */
  jpegData: Buffer
}
export declare function sendStreamThumbnail(args: SendStreamThumbnailArgs): Promise<void>
/**
 * Native encoder capability returned by `probe_native_encoders`.
 * Same shape the renderer's WebCodecs probe used to populate.
 */
export interface NativeEncoderCap {
  /** VideoCodec wire id (1=H264_HW, 3=H265, 4=AV1). */
  codec: number
  maxWidth: number
  maxHeight: number
  maxFps: number
  hardware: boolean
  /** FFmpeg encoder name that actually opens (e.g. "h264_nvenc"). */
  encoderName: string
}
/**
 * Runs the native FFmpeg encoder probe. Windows-only. Returns the
 * list of (codec, vendor) tuples that successfully opened.
 */
export declare function probeNativeEncoders(): Array<NativeEncoderCap>
/**
 * Force the next encoded frame on the active stream (if any) to be a
 * keyframe. Wired from the renderer's `keyframe_requested` event.
 * On Linux/macOS this is a no-op stub — the renderer's WebCodecs
 * encoder handles keyframe forcing in JS via VideoEncoder.encode's
 * `keyFrame: true` option.
 */
export declare function forceKeyframe(): Promise<void>
export interface JoinVoiceChannelArgs {
  serverId: string
  channelId: string
  /**
   * Per-channel voice bitrate from CommunityAuthResponse. `None`
   * falls back to the default Opus bitrate.
   */
  voiceBitrateKbps?: number
}
export declare function joinVoiceChannel(args: JoinVoiceChannelArgs): Promise<void>
export declare function leaveVoiceChannel(): Promise<void>
export interface SetVoiceMuteArgs {
  muted: boolean
}
export declare function setVoiceMute(args: SetVoiceMuteArgs): Promise<void>
export interface SetVoiceDeafenArgs {
  deafened: boolean
}
export declare function setVoiceDeafen(args: SetVoiceDeafenArgs): Promise<void>
export interface SetVoiceThresholdArgs {
  thresholdDb: number
}
export declare function setVoiceThreshold(args: SetVoiceThresholdArgs): Promise<void>
export interface SetStreamVolumeArgs {
  volume: number
}
export declare function setStreamVolume(args: SetStreamVolumeArgs): Promise<void>
export interface SetStreamStereoArgs {
  enabled: boolean
}
export declare function setStreamStereo(args: SetStreamStereoArgs): Promise<void>
export interface SetUserVolumeArgs {
  username: string
  gain: number
}
export declare function setUserVolume(args: SetUserVolumeArgs): Promise<void>
export interface SetAecEnabledArgs {
  enabled: boolean
}
export declare function setAecEnabled(args: SetAecEnabledArgs): Promise<void>
export interface SetNoiseSuppressionLevelArgs {
  level: number
}
export declare function setNoiseSuppressionLevel(args: SetNoiseSuppressionLevelArgs): Promise<void>
export interface SetAgcEnabledArgs {
  enabled: boolean
}
export declare function setAgcEnabled(args: SetAgcEnabledArgs): Promise<void>
export interface SetInputDeviceArgs {
  /** `None` falls back to the system default. */
  name?: string
}
export declare function setInputDevice(args: SetInputDeviceArgs): Promise<void>
export interface SetOutputDeviceArgs {
  name?: string
}
export declare function setOutputDevice(args: SetOutputDeviceArgs): Promise<void>
export interface SetSeparateStreamOutputArgs {
  enabled: boolean
  device?: string
}
export declare function setSeparateStreamOutput(args: SetSeparateStreamOutputArgs): Promise<void>
export interface SetStreamOutputDeviceArgs {
  name?: string
}
export declare function setStreamOutputDevice(args: SetStreamOutputDeviceArgs): Promise<void>
/**
 * Boot-time options pushed in from Electron main. Everything platform-
 * path-shaped (userData, cache) is resolved Node-side via
 * `app.getPath()` and shipped here so Rust never has to figure out
 * platform-specific dirs itself — the Electron main process is the
 * authority.
 */
export interface InitOptions {
  userDataDir: string
  cacheDir: string
  appVersion: string
}
/**
 * Called once from Electron main after `app.whenReady()` and the
 * first BrowserWindow has been created. Installs the EventBus TSFN
 * (so any thread can `events::send(...)`) and stashes BootConfig so
 * any module can read paths via `state::boot()`.
 *
 * Sync, not async — the JsFunction handle has to be turned into a
 * ThreadsafeFunction before any await point.
 */
export declare function init(opts: InitOptions, bus: (...args: any[]) => any, streamBus: (...args: any[]) => any, streamThumbnailBus: (...args: any[]) => any): void
/**
 * Called from Electron main on `before-quit`. Drops engines, joins
 * long-lived threads, releases TLS connections so the process can
 * exit cleanly.
 *
 * Without this, closing the BrowserWindow leaves the main process
 * hanging — the native tokio runtime holds a never-ending thumbnail
 * task, the capture + encoder std::threads sit in their poll loops,
 * and napi-rs's tokio runtime won't drop until those exit. The user
 * then has to kill `decibell.exe` from Task Manager.
 *
 * Resetting AppState to default explicitly drops each engine; their
 * `Drop` impls handle the actual teardown:
 *   - VideoEngine::stop_windows() joins capture + encoder threads
 *     and aborts the thumbnail tokio task
 *   - AudioStreamEngine::stop() joins the share-audio thread
 *   - VoiceEngine::stop() joins audio + video-recv threads and
 *     aborts the event bridge
 *   - CommunityClient / CentralClient drops close their TLS sockets
 */
export declare function shutdown(): Promise<void>
export declare function ping(): string
export declare function pingAsync(): Promise<string>
